[book]
title = "Язык программирования Ржавчина"
author = "Стив Клабник, Кэрол Николс и другие участники сообщества Ржавчины"
language = "ru-RU"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
